// Auto-generated Arduino file in example.c
// Generated by createheader.py at 2015-04-18T15:39:25.296693
#include <Servo.h>

#define SERVO_ELBOW servo[0]
#define RED_LED 6

int servoPorts[] = {9};
Servo servos[1];

void setup()
{
  Serial.begin(9600);
  pinMode(1, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(2, INPUT);
  pinMode(4, INPUT);
  pinMode(6, OUTPUT);
/*  pinMode(22, OUTPUT);
  pinMode(23, OUTPUT);
  pinMode(24, OUTPUT);
  pinMode(25, OUTPUT);
  pinMode(26, OUTPUT);
  pinMode(27, OUTPUT); */ // for debugging
  servos[0].attach(9);
}

bool isServo(int port)
{
  for (int i = 0; i < sizeof(servos) / sizeof(servos[0]); i++)
  {
    if (servoPorts[i] == port)
      return true;
  }
  return false;
}

int getServoIndex(int pin)
{
  switch (pin)
  {
    case 9: return 0;
    default: -1;
  }
  delay(10);
}


// End of autogenerated part

enum pinModes {IN, OUT, SERVO};
enum actions {GET, SET};

int action, port, command;
void loop()
{
//  digitalWrite(24, HIGH); // started
  if (Serial.available() >= 3)
  {
    action = Serial.read(); // 0 = get, 1 = set.
    port = Serial.read();  // 0-13: PWM; 14-21: Communication; 22-53: Digital; 100-115: Analog
    command = Serial.read();

    if (action == 0) // get
    {
  //    digitalWrite(27, HIGH); //debug purposes
      if ((2 <= port && port <= 13) || (100 <= port && port <= 115))  // Read analog or pwm pins
      {
//        digitalWrite(25, HIGH); //debug purposes
        Serial.write(analogRead(port) / 4); // scales from 0 and 255
        Serial.write(10); 
        Serial.write(255); 
      }
      else if (22 <= port && port <= 53)  // write 1 for HIGH and 0 for LOW.
      {
  //      digitalWrite(26, HIGH); //debug purposes
      if (digitalRead(port) == HIGH)
          Serial.write(1);
        else
          Serial.write(0);
      }
    }
    else if (action == 1) //set
    {
//      digitalWrite(22, HIGH); //reading values 
      if (2 <= port && port <= 13)  //if we have an analog port, pass the command directly
      {
//        digitalWrite(23, HIGH); //debug purposes
        if (isServo(port))
        {
          servos[getServoIndex(port)].write(command);
        }
        else
        {
          analogWrite(port, command);
        }
      }
      else if (22 <= port && port <= 53 || 100 <= port && port <= 115)
        // if we have a digital port, 0 and 1 mean LOW and HIGH respectively.
        // note that the analog pins can be used as GPIO too.
      {
        if (command == 0)
        {
          digitalWrite(port, LOW);
        }
        else if (command == 1)
        {
          digitalWrite(port, HIGH);
        }
      }
    }
  }
}
