// Auto-generated Arduino file in example_header.c
// Generated by createheader.py at 2015-04-20T15:16:01.502743

#include <Servo.h>

#define SERVO_ELBOW servo[0]
#define RED_LED 6

int servoPorts[] = {9};
Servo servos[1];

void setup()
{
  Serial.begin(9600); 
  pinMode(1, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(6, OUTPUT);
  pinMode(2, INPUT);
  pinMode(4, INPUT);
  servos[0].attach(9);
}


bool isServo(int port)
{
    for(int i = 0; i < servos.length; i++)
    {
        if (servoPorts[i] == port)
            return true;
    }
    return false;
}

int getServoIndex(int pin)
{
    switch(pin)
        case 9: return 0;
    default -1;
}
